# Generated by Django 4.2.7 on 2025-10-02 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentCreate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='local_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
