# Generated by Django 4.2.7 on 2025-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentCreate', '0002_appointment_local_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ghl_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
